# Generated by Django 5.0.6 on 2026-09-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0002_comment_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedview",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="savedview",
            name="public_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
