# Generated by Django 5.0.6 on 2026-09-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_adminsettings_nav_style_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminsettings",
            name="canvas_background_color",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
